# Use the latest version of MySQL as the base image
FROM mysql:latest

# Modify the UID and GID of the 'mysql' user to be 1000
RUN usermod -u 1000 mysql && groupmod -g 1000 mysql

# Change ownership of the MySQL data directory to the 'mysql' user and group
RUN chown -R mysql:mysql /var/lib/mysql

# Create a directory named 'dump' and set its ownership to the 'mysql' user and group
RUN mkdir /dump
RUN chown -R mysql:mysql /dump